version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "15:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: mocha
    versions:
    - 8.3.1
    - 8.3.2
  - dependency-name: typescript
    versions:
    - 4.2.2
