coverage:
  # How to display and round code coverage
  precision: 2
  round: down
  # Range of coverages to consider "green"
  range: '95...100'
  status:
    #
    project:
      default:
        # Target defines our target coverage number. 'auto' here would uses coverage from the base commit
        target: 100%
        # Threshold defines how much coverage is allowed to drop
        threshold: 0%
    # Measures how well the lines diffed in a PR are tested
    patch:
      default:
        target: 100%
        threshold: 0%
        # Status will fail if no report for the head
        if_not_found: failure

# Configure the PR comments that Codecov leaves
comment:
  # 'reach' is a coverage graph embedded
  # 'diff' is the coverage diff of the PR
  # 'files' are a list of files impacted by the PR
  layout: 'diff, files'
  # Delete old coverage comment and post new one on PR changes
  behavior: new
  # Only post a new comment if coverage changes
  require_changes: true
